services:
  frontend:
    image: evans1304/financial-dashboard-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000

  backend:
    image: evans1304/financial-dashboard-backend:latest
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/mydb

  ai-service:
    image: evans1304/financial-dashboard-ai-service:latest
    ports:
      - "8000:8000"
    depends_on:
      - backend

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
